# Generated by Django 3.1.2 on 2020-12-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newsapp',
            fields=[
                ('id', models.AutoField(max_length=25, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('Email', models.CharField(max_length=50)),
                ('Frequency', models.CharField(max_length=10)),
            ],
        ),
    ]
