# Generated by Django 3.1.2 on 2020-12-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsapp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
