# Generated by Django 3.1.2 on 2020-12-20 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0002_auto_20201220_2200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsapp',
            new_name='Contact',
        ),
    ]
