# Generated by Django 3.1.2 on 2020-12-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_auto_20201220_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Frequency',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Name',
            new_name='name',
        ),
    ]
