# Generated by Django 3.1.2 on 2020-12-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_auto_20201221_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='topnews',
            field=models.BooleanField(default=False),
        ),
    ]
