# Generated by Django 3.1.2 on 2020-12-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0007_auto_20201226_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='topnews',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
