# Generated by Django 3.1.2 on 2020-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0009_auto_20201226_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='wnews',
            field=models.BooleanField(null=True),
        ),
    ]
