# Generated by Django 3.1.2 on 2020-12-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0010_contact_wnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='bnews',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='snews',
            field=models.BooleanField(null=True),
        ),
    ]
